export const RandomData = [
  {
    id: 1,
    name: 'How do I find my blood type?',
    options: [
      'Through a blood test at a medical facility',
      'By guessing based on family history',
      'By analyzing diet preferences',
      'Through a skin test',
    ],
    correctOptions: 'Through a blood test at a medical facility',
    slug: 'how-do-i-find-my-blood-type',
  },
  {
    id: 2,
    name: 'How do I test my IQ?',
    options: [
      'By taking an IQ test administered by a psychologist',
      'By solving daily crossword puzzles',
      'By calculating it from my grades',
      'By checking my birth certificate',
    ],
    correctOptions: 'By taking an IQ test administered by a psychologist',
    slug: 'how-do-i-test-my-iq',
  },
  {
    id: 3,
    name: 'How can I boost my IQ?',
    options: [
      'By engaging in brain-training activities',
      'By eating spicy foods',
      'By sleeping less',
      'By avoiding all mental challenges',
    ],
    correctOptions: 'By engaging in brain-training activities',
    slug: 'how-can-i-boost-my-iq',
  },
  {
    id: 4,
    name: 'How can I increase my IQ?',
    options: [
      'By reading, learning new skills, and problem-solving',
      'By watching TV for extended hours',
      'By consuming sugary foods',
      'By avoiding mental stimulation',
    ],
    correctOptions: 'By reading, learning new skills, and problem-solving',
    slug: 'how-can-i-increase-my-iq',
  },
  {
    id: 5,
    name: 'What blood type do mosquitoes like?',
    options: ['Type O', 'Type A', 'Type B', 'Type AB'],
    correctOptions: 'Type O',
    slug: 'what-blood-type-do-mosquitoes-like',
  },
  {
    id: 6,
    name: 'What IQ is considered genius level?',
    options: ['130 or above', '90-100', '70-80', '50 or below'],
    correctOptions: '130 or above',
    slug: 'what-iq-is-considered-genius-level',
  },
  {
    id: 7,
    name: 'Which blood group is rare?',
    options: ['AB-', 'O+', 'A+', 'B+'],
    correctOptions: 'AB-',
    slug: 'which-blood-group-is-rare',
  },
  {
    id: 8,
    name: 'Which is the strongest blood group?',
    options: ['O-', 'A+', 'B-', 'AB+'],
    correctOptions: 'O-',
    slug: 'which-is-the-strongest-blood-group',
  },
  {
    id: 9,
    name: 'What are the three smallest bones in the human body?',
    options: [
      'Stapes, Incus, Malleus',
      'Stapes, Incus, Hyoid',
      'Malleus, Incus, Femur',
      'Stapes, Incus, Clavicle',
    ],
    correctOptions: 'Stapes, Incus, Malleus',
    slug: 'what-are-the-three-smallest-bones-in-the-human-body',
  },
  {
    id: 10,
    name: 'Can blood type change?',
    options: [
      'Yes, with medical procedures',
      'No, blood type is permanent',
      'Yes, due to lifestyle changes',
      'No, blood type can only be tested, not changed',
    ],
    correctOptions: 'No, blood type is permanent',
    slug: 'can-blood-type-change',
  },
  {
    id: 11,
    name: 'Can IQ be increased?',
    options: [
      'Yes, through mental exercises',
      'No, IQ is fixed at birth',
      'Yes, with medication',
      'No, it can only be measured, not changed',
    ],
    correctOptions: 'Yes, through mental exercises',
    slug: 'can-iq-be-increased',
  },
  {
    id: 12,
    name: 'Can O+ donate to anyone?',
    options: [
      'Yes, to any blood type',
      'No, only to O+ and O-',
      'Yes, but only to A+ and B+',
      'No, it can only donate to O+',
    ],
    correctOptions: 'Yes, to any blood type',
    slug: 'can-o-plus-donate-to-anyone',
  },
  {
    id: 13,
    name: 'How can I increase brain power?',
    options: [
      'Regular exercise and mental challenges',
      'Eating specific foods only',
      'Taking brain supplements',
      'By increasing sleep duration',
    ],
    correctOptions: 'Regular exercise and mental challenges',
    slug: 'how-can-i-increase-brain-power',
  },
  {
    id: 14,
    name: 'How do I check my IQ?',
    options: [
      'Through an online test',
      'By visiting a psychologist',
      'Using a self-assessment tool',
      'No method is accurate',
    ],
    correctOptions: 'By visiting a psychologist',
    slug: 'how-do-i-check-my-iq',
  },
  {
    id: 15,
    name: 'How many blood tests are typically done during pregnancy?',
    options: ['1-2 tests', '3-4 tests', '5-6 tests', 'More than 6 tests'],
    correctOptions: '3-4 tests',
    slug: 'how-many-blood-tests-during-pregnancy',
  },
  {
    id: 16,
    name: 'How many days does it typically take to confirm pregnancy?',
    options: ['1-3 days', '7-10 days', '14-21 days', '30 days'],
    correctOptions: '7-10 days',
    slug: 'how-many-days-to-confirm-pregnancy',
  },
  {
    id: 17,
    name: 'How to calculate IQ?',
    options: [
      'Through standardized testing',
      'Using online IQ calculators',
      'By comparing to average scores',
      'No calculation method is accurate',
    ],
    correctOptions: 'Through standardized testing',
    slug: 'how-to-calculate-iq',
  },
  {
    id: 18,
    name: 'How to check your IQ?',
    options: [
      'Through a certified IQ test',
      'By taking online quizzes',
      'Using a self-assessment tool',
      'No method is reliable',
    ],
    correctOptions: 'Through a certified IQ test',
    slug: 'how-to-check-your-iq',
  },
  {
    id: 19,
    name: 'How to fall pregnant fast?',
    options: [
      'Track ovulation and maintain a healthy lifestyle',
      'Try different positions during intercourse',
      'Increase frequency of intercourse',
      'Consult a fertility specialist',
    ],
    correctOptions: 'Track ovulation and maintain a healthy lifestyle',
    slug: 'how-to-fall-pregnant-fast',
  },
  {
    id: 20,
    name: 'Is 120 IQ good?',
    options: [
      'Yes, it is above average',
      'No, it is below average',
      'Yes, it is exceptional',
      'No, it is average',
    ],
    correctOptions: 'Yes, it is above average',
    slug: 'is-120-iq-good',
  },
  {
    id: 21,
    name: 'Is 130 IQ good?',
    options: [
      'Yes, it is above average',
      'No, it is below average',
      'Yes, it is considered high',
      'No, it is average',
    ],
    correctOptions: 'Yes, it is considered high',
    slug: 'is-130-iq-good',
  },
  {
    id: 22,
    name: 'Is AB+ blood rare?',
    options: [
      'Yes, it is one of the rarest types',
      'No, it is common',
      'Yes, but not very rare',
      'No, it is the most common type',
    ],
    correctOptions: 'Yes, it is one of the rarest types',
    slug: 'is-ab-plus-blood-rare',
  },
  {
    id: 23,
    name: 'Is IQ genetic?',
    options: [
      'Yes, genetics play a significant role',
      'No, IQ is entirely environmental',
      'Yes, but environmental factors are more significant',
      'No, IQ is influenced by education only',
    ],
    correctOptions: 'Yes, genetics play a significant role',
    slug: 'is-iq-genetic',
  },
  {
    id: 24,
    name: 'What blood type am I?',
    options: ['A, B, AB, or O', 'Positive or Negative', 'A or B', 'AB or O'],
    correctOptions: 'A, B, AB, or O',
    slug: 'what-blood-type-am-i',
  },
  {
    id: 25,
    name: 'What blood type rejects pregnancy?',
    options: [
      'Rh-negative blood type',
      'Rh-positive blood type',
      'Type O blood type',
      'Type A blood type',
    ],
    correctOptions: 'Rh-negative blood type',
    slug: 'what-blood-type-rejects-pregnancy',
  },
  {
    id: 26,
    name: 'What is a normal IQ?',
    options: ['Around 100', 'Around 120', 'Around 80', 'Around 140'],
    correctOptions: 'Around 100',
    slug: 'what-is-a-normal-iq',
  },
  {
    id: 27,
    name: "What is Albert Einstein's IQ?",
    options: ['160', '180', '150', '190'],
    correctOptions: '160',
    slug: 'what-is-albert-einsteins-iq',
  },
  {
    id: 28,
    name: "What is Einstein's IQ?",
    options: ['160', '180', '150', '190'],
    correctOptions: '160',
    slug: 'what-is-einsteins-iq',
  },
]
