export const RandomData = [
  {
    id: 1,
    name: 'How do I find my blood type?',
    options: [
      'Through a blood test at a medical facility',
      'By guessing based on family history',
      'By analyzing diet preferences',
      'Through a skin test',
    ],
    correctOptions: 'Through a blood test at a medical facility',
    slug: 'how-do-i-find-my-blood-type',
  },
  {
    id: 2,
    name: 'How do I test my IQ?',
    options: [
      'By taking an IQ test administered by a psychologist',
      'By solving daily crossword puzzles',
      'By calculating it from my grades',
      'By checking my birth certificate',
    ],
    correctOptions: 'By taking an IQ test administered by a psychologist',
    slug: 'how-do-i-test-my-iq',
  },
  {
    id: 3,
    name: 'How can I boost my IQ?',
    options: [
      'By engaging in brain-training activities',
      'By eating spicy foods',
      'By sleeping less',
      'By avoiding all mental challenges',
    ],
    correctOptions: 'By engaging in brain-training activities',
    slug: 'how-can-i-boost-my-iq',
  },
  {
    id: 4,
    name: 'How can I increase my IQ?',
    options: [
      'By reading, learning new skills, and problem-solving',
      'By watching TV for extended hours',
      'By consuming sugary foods',
      'By avoiding mental stimulation',
    ],
    correctOptions: 'By reading, learning new skills, and problem-solving',
    slug: 'how-can-i-increase-my-iq',
  },
  {
    id: 5,
    name: 'What blood type do mosquitoes like?',
    options: ['Type O', 'Type A', 'Type B', 'Type AB'],
    correctOptions: 'Type O',
    slug: 'what-blood-type-do-mosquitoes-like',
  },
  {
    id: 6,
    name: 'What IQ is considered genius level?',
    options: ['130 or above', '90-100', '70-80', '50 or below'],
    correctOptions: '130 or above',
    slug: 'what-iq-is-considered-genius-level',
  },
  {
    id: 7,
    name: 'Which blood group is rare?',
    options: ['AB-', 'O+', 'A+', 'B+'],
    correctOptions: 'AB-',
    slug: 'which-blood-group-is-rare',
  },
  {
    id: 8,
    name: 'Which is the strongest blood group?',
    options: ['O-', 'A+', 'B-', 'AB+'],
    correctOptions: 'O-',
    slug: 'which-is-the-strongest-blood-group',
  },
  {
    id: 9,
    name: 'What are the three smallest bones in the human body?',
    options: [
      'Stapes, Incus, Malleus',
      'Stapes, Incus, Hyoid',
      'Malleus, Incus, Femur',
      'Stapes, Incus, Clavicle',
    ],
    correctOptions: 'Stapes, Incus, Malleus',
    slug: 'what-are-the-three-smallest-bones-in-the-human-body',
  },
  {
    id: 10,
    name: 'Can blood type change?',
    options: [
      'Yes, with medical procedures',
      'No, blood type is permanent',
      'Yes, due to lifestyle changes',
      'No, blood type can only be tested, not changed',
    ],
    correctOptions: 'No, blood type is permanent',
    slug: 'can-blood-type-change',
  },
  {
    id: 11,
    name: 'Can IQ be increased?',
    options: [
      'Yes, through mental exercises',
      'No, IQ is fixed at birth',
      'Yes, with medication',
      'No, it can only be measured, not changed',
    ],
    correctOptions: 'Yes, through mental exercises',
    slug: 'can-iq-be-increased',
  },
  {
    id: 12,
    name: 'Can O+ donate to anyone?',
    options: [
      'Yes, to any blood type',
      'No, only to O+ and O-',
      'Yes, but only to A+ and B+',
      'No, it can only donate to O+',
    ],
    correctOptions: 'Yes, to any blood type',
    slug: 'can-o-plus-donate-to-anyone',
  },
  {
    id: 13,
    name: 'How can I increase brain power?',
    options: [
      'Regular exercise and mental challenges',
      'Eating specific foods only',
      'Taking brain supplements',
      'By increasing sleep duration',
    ],
    correctOptions: 'Regular exercise and mental challenges',
    slug: 'how-can-i-increase-brain-power',
  },
  {
    id: 14,
    name: 'How do I check my IQ?',
    options: [
      'Through an online test',
      'By visiting a psychologist',
      'Using a self-assessment tool',
      'No method is accurate',
    ],
    correctOptions: 'By visiting a psychologist',
    slug: 'how-do-i-check-my-iq',
  },
  {
    id: 15,
    name: 'How many blood tests are typically done during pregnancy?',
    options: ['1-2 tests', '3-4 tests', '5-6 tests', 'More than 6 tests'],
    correctOptions: '3-4 tests',
    slug: 'how-many-blood-tests-during-pregnancy',
  },
  {
    id: 16,
    name: 'How many days does it typically take to confirm pregnancy?',
    options: ['1-3 days', '7-10 days', '14-21 days', '30 days'],
    correctOptions: '7-10 days',
    slug: 'how-many-days-to-confirm-pregnancy',
  },
  {
    id: 17,
    name: 'How to calculate IQ?',
    options: [
      'Through standardized testing',
      'Using online IQ calculators',
      'By comparing to average scores',
      'No calculation method is accurate',
    ],
    correctOptions: 'Through standardized testing',
    slug: 'how-to-calculate-iq',
  },
  {
    id: 18,
    name: 'How to check your IQ?',
    options: [
      'Through a certified IQ test',
      'By taking online quizzes',
      'Using a self-assessment tool',
      'No method is reliable',
    ],
    correctOptions: 'Through a certified IQ test',
    slug: 'how-to-check-your-iq',
  },
  {
    id: 19,
    name: 'How to fall pregnant fast?',
    options: [
      'Track ovulation and maintain a healthy lifestyle',
      'Try different positions during intercourse',
      'Increase frequency of intercourse',
      'Consult a fertility specialist',
    ],
    correctOptions: 'Track ovulation and maintain a healthy lifestyle',
    slug: 'how-to-fall-pregnant-fast',
  },
  {
    id: 20,
    name: 'Is 120 IQ good?',
    options: [
      'Yes, it is above average',
      'No, it is below average',
      'Yes, it is exceptional',
      'No, it is average',
    ],
    correctOptions: 'Yes, it is above average',
    slug: 'is-120-iq-good',
  },
  {
    id: 21,
    name: 'Is 130 IQ good?',
    options: [
      'Yes, it is above average',
      'No, it is below average',
      'Yes, it is considered high',
      'No, it is average',
    ],
    correctOptions: 'Yes, it is considered high',
    slug: 'is-130-iq-good',
  },
  {
    id: 22,
    name: 'Is AB+ blood rare?',
    options: [
      'Yes, it is one of the rarest types',
      'No, it is common',
      'Yes, but not very rare',
      'No, it is the most common type',
    ],
    correctOptions: 'Yes, it is one of the rarest types',
    slug: 'is-ab-plus-blood-rare',
  },
  {
    id: 23,
    name: 'Is IQ genetic?',
    options: [
      'Yes, genetics play a significant role',
      'No, IQ is entirely environmental',
      'Yes, but environmental factors are more significant',
      'No, IQ is influenced by education only',
    ],
    correctOptions: 'Yes, genetics play a significant role',
    slug: 'is-iq-genetic',
  },
  {
    id: 24,
    name: 'What blood type am I?',
    options: ['A, B, AB, or O', 'Positive or Negative', 'A or B', 'AB or O'],
    correctOptions: 'A, B, AB, or O',
    slug: 'what-blood-type-am-i',
  },
  {
    id: 25,
    name: 'What blood type rejects pregnancy?',
    options: [
      'Rh-negative blood type',
      'Rh-positive blood type',
      'Type O blood type',
      'Type A blood type',
    ],
    correctOptions: 'Rh-negative blood type',
    slug: 'what-blood-type-rejects-pregnancy',
  },
  {
    id: 26,
    name: 'What is a normal IQ?',
    options: ['Around 100', 'Around 120', 'Around 80', 'Around 140'],
    correctOptions: 'Around 100',
    slug: 'what-is-a-normal-iq',
  },
  {
    id: 27,
    name: "What is Albert Einstein's IQ?",
    options: ['160', '180', '150', '190'],
    correctOptions: '160',
    slug: 'what-is-albert-einsteins-iq',
  },
  {
    id: 28,
    name: "What is Einstein's IQ?",
    options: ['160', '180', '150', '190'],
    correctOptions: '160',
    slug: 'what-is-einsteins-iq',
  },
  {
    id: 29,
    name: 'Which is the largest island in the world?',
    options: ['Greenland', 'Australia', 'New Guinea', 'Borneo'],
    correctOptions: 'Greenland',
    slug: 'which-is-the-largest-island-in-the-world',
  },
  {
    id: 30,
    name: 'Is Australia an island?',
    options: [
      'Yes',
      'No',
      'It is a continent',
      'It is both an island and a continent',
    ],
    correctOptions: 'It is a continent',
    slug: 'is-australia-an-island',
  },
  {
    id: 31,
    name: 'Is Greenland a country?',
    options: [
      'Yes',
      'No, it is part of Denmark',
      'No, it is a province',
      'Yes, but with limited sovereignty',
    ],
    correctOptions: 'No, it is part of Denmark',
    slug: 'is-greenland-a-country',
  },
  {
    id: 32,
    name: "What is the world's largest island?",
    options: ['Greenland', 'Australia', 'New Guinea', 'Borneo'],
    correctOptions: 'Greenland',
    slug: 'what-is-the-worlds-largest-island',
  },
  {
    id: 33,
    name: 'Where is Greenland located?',
    options: ['North America', 'Europe', 'Asia', 'Antarctica'],
    correctOptions: 'North America',
    slug: 'where-is-greenland-located',
  },
  {
    id: 34,
    name: 'Which island is the largest in the world?',
    options: ['Greenland', 'Australia', 'New Guinea', 'Borneo'],
    correctOptions: 'Greenland',
    slug: 'which-island-is-the-largest-in-the-world',
  },

  {
    id: 35,
    name: 'Do people live in Greenland?',
    options: ['Yes', 'No', 'Only scientists', 'Only during the summer'],
    correctOptions: 'Yes',
    slug: 'do-people-live-in-greenland',
  },
  {
    id: 36,
    name: 'Does Antarctica have a flag?',
    options: [
      'Yes',
      'No',
      'Only for research stations',
      'It has a symbolic flag',
    ],
    correctOptions: 'It has a symbolic flag',
    slug: 'does-antarctica-have-a-flag',
  },
  {
    id: 37,
    name: 'In which continent is Greenland?',
    options: ['North America', 'Europe', 'Asia', 'Antarctica'],
    correctOptions: 'North America',
    slug: 'in-which-continent-is-greenland',
  },
  {
    id: 38,
    name: 'Is Australia bigger than the USA?',
    options: [
      'Yes',
      'No',
      'They are the same size',
      'Australia is slightly smaller',
    ],
    correctOptions: 'No',
    slug: 'is-australia-bigger-than-the-usa',
  },
  {
    id: 39,
    name: 'Is Greenland part of Europe?',
    options: ['Yes', 'No', 'Only politically', 'Only geographically'],
    correctOptions: 'No',
    slug: 'is-greenland-part-of-europe',
  },
  {
    id: 40,
    name: 'What does the Israel flag look like?',
    options: [
      'Blue and white with a Star of David',
      'Blue and yellow with a Star of David',
      'Red and white with a Star of David',
      'Black and white with a Star of David',
    ],
    correctOptions: 'Blue and white with a Star of David',
    slug: 'what-does-the-israel-flag-look-like',
  },
  {
    id: 41,
    name: 'What flag is black, red, and yellow?',
    options: ['Germany', 'Belgium', 'Spain', 'Colombia'],
    correctOptions: 'Germany',
    slug: 'what-flag-is-black-red-and-yellow',
  },
  {
    id: 42,
    name: 'What flag is blue and yellow?',
    options: ['Sweden', 'Ukraine', 'Kazakhstan', 'Brazil'],
    correctOptions: 'Ukraine',
    slug: 'what-flag-is-blue-and-yellow',
  },
  {
    id: 43,
    name: 'What is Denmark famous for?',
    options: ['Lego', 'Vikings', 'Fairy tales', 'All of the above'],
    correctOptions: 'All of the above',
    slug: 'what-is-denmark-famous-for',
  },
  {
    id: 44,
    name: 'What is the biggest island in the world?',
    options: ['Greenland', 'Australia', 'New Guinea', 'Borneo'],
    correctOptions: 'Greenland',
    slug: 'what-is-the-biggest-island-in-the-world',
  },
  {
    id: 45,
    name: 'What language is spoken in Greenland?',
    options: ['Greenlandic', 'Danish', 'Inuit languages', 'All of the above'],
    correctOptions: 'All of the above',
    slug: 'what-language-is-spoken-in-greenland',
  },
  {
    id: 46,
    name: 'Which country is closest to the equator?',
    options: ['Ecuador', 'Kenya', 'Brazil', 'Indonesia'],
    correctOptions: 'Ecuador',
    slug: 'which-country-is-closest-to-the-equator',
  },
  {
    id: 47,
    name: 'Which is bigger, Greenland or Australia?',
    options: [
      'Australia',
      'Greenland',
      'They are the same size',
      'Greenland is slightly bigger',
    ],
    correctOptions: 'Australia',
    slug: 'which-is-bigger-greenland-or-australia',
  },
  {
    id: 48,
    name: 'Which is larger, Greenland or the USA?',
    options: [
      'The USA',
      'Greenland',
      'They are the same size',
      'Greenland is slightly larger',
    ],
    correctOptions: 'The USA',
    slug: 'which-is-larger-greenland-or-usa',
  },
  {
    id: 49,
    name: 'Who discovered Greenland?',
    options: [
      'Erik the Red',
      'Christopher Columbus',
      'Leif Erikson',
      'Marco Polo',
    ],
    correctOptions: 'Erik the Red',
    slug: 'who-discovered-greenland',
  },
  {
    id: 50,
    name: 'Who founded Greenland?',
    options: [
      'Erik the Red',
      'Leif Erikson',
      'Christopher Columbus',
      'Vikings',
    ],
    correctOptions: 'Erik the Red',
    slug: 'who-founded-greenland',
  },
  {
    id: 51,
    name: 'Who owns Greenland?',
    options: ['Denmark', 'Greenland', 'Canada', 'USA'],
    correctOptions: 'Denmark',
    slug: 'who-owns-greenland',
  },
  {
    id: 52,
    name: 'Why is it called Greenland?',
    options: [
      'To attract settlers',
      'Because of its green valleys',
      'It was named by Vikings',
      'It is a translation error',
    ],
    correctOptions: 'To attract settlers',
    slug: 'why-is-it-called-greenland',
  },

  {
    id: 53,
    name: 'Are there trees in Greenland?',
    options: ['Yes', 'No', 'Only in certain areas', 'Only in the south'],
    correctOptions: 'Only in certain areas',
    slug: 'are-there-trees-in-greenland',
  },
  {
    id: 54,
    name: 'Can you live in Greenland?',
    options: [
      'Yes',
      'No',
      'Only during the summer',
      'Only for research purposes',
    ],
    correctOptions: 'Yes',
    slug: 'can-you-live-in-greenland',
  },
  {
    id: 55,
    name: 'Does Greenland have a military?',
    options: [
      'Yes',
      'No',
      'Only a small defense force',
      'It relies on Denmark for defense',
    ],
    correctOptions: 'It relies on Denmark for defense',
    slug: 'does-greenland-have-a-military',
  },
  {
    id: 56,
    name: 'Greenland or Iceland?',
    options: [
      'Greenland is larger',
      'Iceland is larger',
      'They are the same size',
      'Iceland is colder',
    ],
    correctOptions: 'Greenland is larger',
    slug: 'greenland-or-iceland',
  },
  {
    id: 57,
    name: 'How large is Greenland?',
    options: [
      '2.16 million square kilometers',
      '1.5 million square kilometers',
      '3.2 million square kilometers',
      '1 million square kilometers',
    ],
    correctOptions: '2.16 million square kilometers',
    slug: 'how-large-is-greenland',
  },
  {
    id: 58,
    name: 'How many cities are in Greenland?',
    options: ['3', '5', '10', '15'],
    correctOptions: '3',
    slug: 'how-many-cities-are-in-greenland',
  },
  {
    id: 59,
    name: 'Is Australia the largest island in the world?',
    options: ['Yes', 'No, Greenland is', 'No, New Guinea is', 'No, Borneo is'],
    correctOptions: 'No, Greenland is',
    slug: 'is-australia-the-largest-island-in-the-world',
  },
  {
    id: 60,
    name: 'Is Greenland a country, yes or no?',
    options: [
      'Yes',
      'No',
      'It is a self-governing territory',
      'It has limited sovereignty',
    ],
    correctOptions: 'No',
    slug: 'is-greenland-a-country-yes-or-no',
  },
  {
    id: 61,
    name: 'Is Greenland bigger than Africa?',
    options: [
      'Yes',
      'No',
      'They are about the same size',
      'Greenland is slightly bigger',
    ],
    correctOptions: 'No',
    slug: 'is-greenland-bigger-than-africa',
  },
  {
    id: 62,
    name: 'Is Greenland bigger than Canada?',
    options: [
      'Yes',
      'No',
      'They are about the same size',
      'Greenland is slightly bigger',
    ],
    correctOptions: 'No',
    slug: 'is-greenland-bigger-than-canada',
  },
  {
    id: 63,
    name: 'Is Greenland bigger than India?',
    options: [
      'Yes',
      'No',
      'They are about the same size',
      'Greenland is slightly bigger',
    ],
    correctOptions: 'Yes',
    slug: 'is-greenland-bigger-than-india',
  },
  {
    id: 64,
    name: 'Is Greenland in NATO?',
    options: ['Yes', 'No', 'Only Denmark is a member', 'It is a future member'],
    correctOptions: 'No',
    slug: 'is-greenland-in-nato',
  },
  {
    id: 65,
    name: 'What is Greenland known for?',
    options: ['Ice sheets', 'Vikings', 'Polar bears', 'All of the above'],
    correctOptions: 'All of the above',
    slug: 'what-is-greenland-known-for',
  },
  {
    id: 66,
    name: 'What is the oldest flag?',
    options: ['Denmark', 'Sweden', 'Scotland', 'Nepal'],
    correctOptions: 'Denmark',
    slug: 'what-is-the-oldest-flag',
  },
  {
    id: 67,
    name: 'What is the smallest continent on Earth?',
    options: ['Australia', 'Europe', 'Antarctica', 'South America'],
    correctOptions: 'Australia',
    slug: 'what-is-the-smallest-continent-on-earth',
  },
  {
    id: 68,
    name: 'Which country has the best army?',
    options: ['United States', 'China', 'Russia', 'India'],
    correctOptions: 'United States',
    slug: 'which-country-has-the-best-army',
  },
  {
    id: 69,
    name: 'Which country is both an island and a continent?',
    options: ['Australia', 'Greenland', 'Iceland', 'New Zealand'],
    correctOptions: 'Australia',
    slug: 'which-country-is-both-an-island-and-a-continent',
  },
  {
    id: 70,
    name: 'Which country owns Greenland?',
    options: ['Denmark', 'Iceland', 'Norway', 'Sweden'],
    correctOptions: 'Denmark',
    slug: 'which-country-owns-greenland',
  },
  {
    id: 71,
    name: "Which country's flag is blue, white, and red?",
    options: ['France', 'Australia', 'Canada', 'Iceland'],
    correctOptions: 'France',
    slug: 'which-countrys-flag-is-blue-white-and-red',
  },
  {
    id: 72,
    name: 'Who controls Greenland?',
    options: ['Denmark', 'Iceland', 'Norway', 'The United States'],
    correctOptions: 'Denmark',
    slug: 'who-controls-greenland',
  },
  {
    id: 73,
    name: 'Who named Greenland?',
    options: [
      'Eric the Red',
      'Leif Erikson',
      'Christopher Columbus',
      'Vikings',
    ],
    correctOptions: 'Eric the Red',
    slug: 'who-named-greenland',
  },
  {
    id: 74,
    name: 'Who owns Iceland and Greenland?',
    options: ['Denmark', 'Iceland', 'Norway', 'Sweden'],
    correctOptions: 'Denmark',
    slug: 'who-owns-iceland-and-greenland',
  },
  {
    id: 75,
    name: 'Who rules Greenland?',
    options: ['Denmark', 'Iceland', 'Norway', 'The United States'],
    correctOptions: 'Denmark',
    slug: 'who-rules-greenland',
  },
  {
    id: 76,
    name: 'Why is Australia not an island?',
    options: [
      'It is considered a continent',
      'It is too large to be an island',
      'It is surrounded by seas, not just oceans',
      'It is part of Oceania',
    ],
    correctOptions: 'It is considered a continent',
    slug: 'why-is-australia-not-an-island',
  },
  {
    id: 77,
    name: 'Why is Greenland not a continent?',
    options: [
      'It is too small',
      'It is covered in ice',
      'It is part of North America',
      'It is not a landmass but a region',
    ],
    correctOptions: 'It is part of North America',
    slug: 'why-is-greenland-not-a-continent',
  },
  {
    id: 78,
    name: 'Why is Greenland so big on maps?',
    options: [
      'Map projection distortion',
      'It is actually very large',
      'Maps are outdated',
      'It is zoomed in on maps',
    ],
    correctOptions: 'Map projection distortion',
    slug: 'why-is-greenland-so-big-on-maps',
  },
  {
    id: 79,
    name: 'Can I buy land in Greenland?',
    options: [
      'Yes',
      'No',
      'Only with government permission',
      'Only as a foreigner',
    ],
    correctOptions: 'No',
    slug: 'can-i-buy-land-in-greenland',
  },
  {
    id: 80,
    name: 'Is Greenland bigger than China?',
    options: [
      'Yes',
      'No',
      'They are the same size',
      'Greenland is slightly smaller',
    ],
    correctOptions: 'No',
    slug: 'is-greenland-bigger-than-china',
  },
  {
    id: 81,
    name: 'Is Greenland bigger than Iceland?',
    options: [
      'Yes',
      'No',
      'They are the same size',
      'Greenland is slightly smaller',
    ],
    correctOptions: 'Yes',
    slug: 'is-greenland-bigger-than-iceland',
  },
  {
    id: 82,
    name: 'Is it always cold in Greenland?',
    options: ['Yes', 'No', 'Only in winter', 'Only in summer'],
    correctOptions: 'No',
    slug: 'is-it-always-cold-in-greenland',
  },
  {
    id: 83,
    name: 'Is there land under Greenland?',
    options: ['Yes', 'No', 'It is all ice', 'It is ocean'],
    correctOptions: 'Yes',
    slug: 'is-there-land-under-greenland',
  },
  {
    id: 84,
    name: 'What country has a green, yellow, and red flag?',
    options: ['Brazil', 'Mexico', 'Spain', 'France'],
    correctOptions: 'Brazil',
    slug: 'what-country-has-green-yellow-and-red-flag',
  },
  {
    id: 85,
    name: 'What flag is Greece?',
    options: [
      'Blue and white stripes',
      'Red and white',
      'Blue and yellow',
      'Green and white',
    ],
    correctOptions: 'Blue and white stripes',
    slug: 'what-flag-is-greece',
  },
  {
    id: 86,
    name: 'What flag is Saudi Arabia?',
    options: [
      'Green with white script',
      'Red and white stripes',
      'Blue and yellow',
      'Black and white',
    ],
    correctOptions: 'Green with white script',
    slug: 'what-flag-is-saudi-arabia',
  },
  {
    id: 87,
    name: 'What flag is Turkey?',
    options: [
      'Red with white star and crescent',
      'Blue and white stripes',
      'Red and white stripes',
      'Green with white star',
    ],
    correctOptions: 'Red with white star and crescent',
    slug: 'what-flag-is-turkey',
  },
  {
    id: 88,
    name: 'What is special about Greenland?',
    options: [
      'Largest island in the world',
      'Has a unique language',
      'Has no trees',
      'All of the above',
    ],
    correctOptions: 'All of the above',
    slug: 'what-is-special-about-greenland',
  },
  {
    id: 89,
    name: 'What is the culture of Greenland?',
    options: [
      'Inuit culture',
      'Viking culture',
      'Nordic culture',
      'Western culture',
    ],
    correctOptions: 'Inuit culture',
    slug: 'what-is-the-culture-of-greenland',
  },
  {
    id: 90,
    name: 'What is the meaning of Greenland?',
    options: ['Green land', 'Frozen land', 'New land', 'Land of ice'],
    correctOptions: 'Green land',
    slug: 'what-is-the-meaning-of-greenland',
  },
  {
    id: 91,
    name: 'What religion is Greenland?',
    options: ['Christianity', 'Buddhism', 'Islam', 'Hinduism'],
    correctOptions: 'Christianity',
    slug: 'what-religion-is-greenland',
  },
  {
    id: 92,
    name: 'Which country has a black and white flag?',
    options: ['Germany', 'Japan', 'South Korea', 'Monaco'],
    correctOptions: 'Germany',
    slug: 'which-country-has-a-black-and-white-flag',
  },
  {
    id: 93,
    name: 'Which country has green in its flag?',
    options: ['Brazil', 'Japan', 'Russia', 'France'],
    correctOptions: 'Brazil',
    slug: 'which-country-has-green-in-its-flag',
  },
  {
    id: 94,
    name: 'Which country has green, white, and red in its flag?',
    options: ['Mexico', 'India', 'Italy', 'All of the above'],
    correctOptions: 'All of the above',
    slug: 'which-country-has-green-white-and-red',
  },
  {
    id: 95,
    name: 'Which country has a yellow and red flag?',
    options: ['Spain', 'Canada', 'China', 'Japan'],
    correctOptions: 'Spain',
    slug: 'which-country-has-yellow-and-red-flag',
  },
  {
    id: 96,
    name: 'Which country is bigger, Greenland or India?',
    options: [
      'Greenland',
      'India',
      'They are the same size',
      'Greenland is slightly smaller',
    ],
    correctOptions: 'India',
    slug: 'which-country-is-bigger-greenland-or-india',
  },
  {
    id: 97,
    name: 'Which country is colder?',
    options: ['Greenland', 'Iceland', 'Both are the same', 'Neither'],
    correctOptions: 'Greenland',
    slug: 'which-country-is-colder',
  },
  {
    id: 98,
    name: "Which country's flag has red in it?",
    options: ['Canada', 'United Kingdom', 'South Korea', 'All of the above'],
    correctOptions: 'All of the above',
    slug: 'which-countrys-flag-has-red-in-it',
  },
  {
    id: 99,
    name: 'Which flag has a sun on it?',
    options: ['Japan', 'Brazil', 'Argentina', 'Turkey'],
    correctOptions: 'Argentina',
    slug: 'which-flag-has-a-sun-on-it',
  },
  {
    id: 100,
    name: 'Who is the leader of Greenland?',
    options: [
      'Kim Kielsen',
      'Mette Frederiksen',
      'Lars Løkke Rasmussen',
      'Thorvald Stoltenberg',
    ],
    correctOptions: 'Kim Kielsen',
    slug: 'who-is-the-leader-of-greenland',
  },
  {
    id: 101,
    name: 'Who runs Greenland?',
    options: ['Denmark', 'Iceland', 'Norway', 'The United States'],
    correctOptions: 'Denmark',
    slug: 'who-runs-greenland',
  },
  {
    id: 102,
    name: 'Why is Greenland a part of the USA?',
    options: [
      'It is not part of the USA',
      'It was purchased by the USA',
      'It is a territory of Denmark',
      'It is under US administration',
    ],
    correctOptions: 'It is not part of the USA',
    slug: 'why-is-greenland-a-part-of-usa',
  },
  {
    id: 103,
    name: 'Why is Greenland so expensive?',
    options: [
      'High cost of living',
      'Low population density',
      'Remote location',
      'All of the above',
    ],
    correctOptions: 'All of the above',
    slug: 'why-is-greenland-so-expensive',
  },
  {
    id: 104,
    name: 'Why is Greenland so famous?',
    options: [
      'Its ice sheet',
      'Its unique culture',
      'Its strategic location',
      'All of the above',
    ],
    correctOptions: 'All of the above',
    slug: 'why-is-greenland-so-famous',
  },
  {
    id: 105,
    name: 'Why is Greenland very cold?',
    options: [
      'Its polar location',
      'High altitude',
      'Proximity to the Arctic',
      'All of the above',
    ],
    correctOptions: 'All of the above',
    slug: 'why-is-greenland-very-cold',
  },
  {
    id: 106,
    name: 'Why are Iceland and Greenland named opposite?',
    options: [
      'Historical reasons',
      'Geographic features',
      'Discovery myths',
      'Naming conventions',
    ],
    correctOptions: 'Discovery myths',
    slug: 'why-are-iceland-and-greenland-named-opposite',
  },
  {
    id: 107,
    name: 'Why live in Greenland?',
    options: [
      'Unique environment',
      'Cultural experience',
      'Adventure and isolation',
      'All of the above',
    ],
    correctOptions: 'All of the above',
    slug: 'why-live-in-greenland',
  },
  {
    id: 108,
    name: 'What is the total length of Ravi River?',
    options: [
      '500 kilometers',
      '720 kilometers',
      '1000 kilometers',
      '1200 kilometers',
    ],
    correctOption: '720 kilometers',
    slug: 'what-is-the-total-length-of-ravi-river',
  },
  {
    id: 109,
    name: 'In which countries does the Ravi River flow?',
    options: [
      'India and Pakistan',
      'India and China',
      'Pakistan and Afghanistan',
      'India and Nepal',
    ],
    correctOption: 'India and Pakistan',
    slug: 'in-which-countries-does-the-ravi-river-flow',
  },
  {
    id: 110,
    name: 'What is the primary source of the Ravi River?',
    options: [
      'Himalayas',
      'Karakoram Range',
      'Western Ghats',
      'Sulaiman Range',
    ],
    correctOption: 'Himalayas',
    slug: 'what-is-the-primary-source-of-the-ravi-river',
  },
  {
    id: 111,
    name: 'Which major city is located near the Ravi River?',
    options: ['Lahore', 'Karachi', 'Delhi', 'Islamabad'],
    correctOption: 'Lahore',
    slug: 'which-major-city-is-located-near-the-ravi-river',
  },
  {
    id: 112,
    name: 'What type of river is the Ravi River classified as?',
    options: [
      'Glacial river',
      'Mountain river',
      'Plains river',
      'Desert river',
    ],
    correctOption: 'Mountain river',
    slug: 'what-type-of-river-is-the-ravi-river-classified-as',
  },
]
