export const IntroductionToBiology = [
  {
    id: 0,
    questionName: 'Jabir Bin Hayan was born in __________.',
    options: ['Iraq', 'Iran', 'Lebanon', 'Turkey'],
    correctOption: 'Iran',
    description: 'Jabir Bin Hayan was born in Iran.',
    slug: 'jabir-bin-hayan-was-born-in',
  },
  {
    id: 1,
    questionName: '“Al-Haywan” is a famous book by which Muslim scientist?',
    options: [
      'Abdul Malik Asmai',
      'Jabir Bin Hayan',
      'Bu Ali Sina',
      'Omar Khayyam',
    ],
    correctOption: 'Abdul Malik Asmai',
    description: '“Al-Haywan” is a famous book by Abdul Malik Asmai.',
    slug: 'al-haywan-is-a-famous-book-by-which-muslim-scientist',
  },
  {
    id: 2,
    questionName:
      'Who is considered the 1st Muslim scientist that studied animals in detail?',
    options: [
      'Jabir Bin Hayan',
      'Abdul Malik Asmai',
      'Ibn Rushd',
      'Muhammad Ibn Musa Al-Khwarizmi',
    ],
    correctOption: 'Abdul Malik Asmai',
    description:
      'Abdul Malik Asmai is considered the first Muslim scientist that studied animals in detail.',
    slug: 'who-is-considered-the-1st-muslim-scientist-that-studied-animals-in-detail',
  },
  {
    id: 3,
    questionName:
      "Abdul Malik Asmai's famous writing (Al-Khail) means __________.",
    options: ['Camel', 'Horse', 'Animal', 'Plant'],
    correctOption: 'Horse',
    description: "Abdul Malik Asmai's famous writing 'Al-Khail' means Horse.",
    slug: 'abdul-malik-asmais-famous-writing-al-khail-means',
  },
  {
    id: 4,
    questionName: 'Which scientist is called Avicenna in the west?',
    options: [
      'Jabir Bin Hayan',
      'Hippocrates',
      'Bu Ali Sina',
      'Abu Nasr Al-Farabi',
    ],
    correctOption: 'Bu Ali Sina',
    description: 'Bu Ali Sina is called Avicenna in the west.',
    slug: 'which-scientist-is-called-avicenna-in-the-west',
  },
  {
    id: 5,
    questionName: 'Which book is called the “canon of medicine” in the west?',
    options: ['Kalq al-Ansan', 'Al-Nabatat', 'Al-Qanun-fial-Tib', 'Al-chemist'],
    correctOption: 'Al-Qanun-fial-Tib',
    description:
      "The book called the 'canon of medicine' in the west is 'Al-Qanun-fial-Tib'.",
    slug: 'which-book-is-called-the-canon-of-medicine-in-the-west',
  },
  {
    id: 6,
    questionName: 'The life span of Bu Ali Sina is:',
    options: ['900-1000', '800-900', '900-1100', '900-1037'],
    correctOption: '900-1037',
    description: 'The life span of Bu Ali Sina is from 900 to 1037.',
    slug: 'the-life-span-of-bu-ali-sina-is',
  },
  {
    id: 7,
    questionName: 'The life span of Jabir Bin Hayyan is:',
    options: ['900-1037', '740-828', '721-815', '700-800'],
    correctOption: '721-815',
    description: 'The life span of Jabir Bin Hayyan is from 721 to 815.',
    slug: 'the-life-span-of-jabir-bin-hayyan-is',
  },
  {
    id: 8,
    questionName: 'Who is widely considered as father of chemistry?',
    options: [
      'Bu Ali Sina',
      'Jafar Al-Sadiq',
      'Jabir bin Hayyan',
      'Abdul Malik Asmai',
    ],
    correctOption: 'Jabir bin Hayyan',
    description:
      'Jabir bin Hayyan is widely considered the father of chemistry.',
    slug: 'who-is-widely-considered-as-father-of-chemistry',
  },
  {
    id: 9,
    questionName: 'The author of “Al-Qanun-fial-Tib” is:',
    options: ['Jabin Bin Hayan', 'Abdul Malik Asmai', 'Bu Ali Sina', 'None'],
    correctOption: 'Bu Ali Sina',
    description: "The author of 'Al-Qanun-fial-Tib' is Bu Ali Sina.",
    slug: 'the-author-of-al-qanun-fial-tib-is',
  },
  {
    id: 10,
    questionName: 'Which one of the following books is about camels?',
    options: ['As Sha', 'Al-Ibil', 'Al-Kheil', 'Al Wahoosh'],
    correctOption: 'Al-Ibil',
    description: "The book about camels is 'Al-Ibil'.",
    slug: 'which-one-of-the-following-books-is-about-camels',
  },
  {
    id: 11,
    questionName: 'Which one of the following book is about horses?',
    options: ['Al Wahoosh', 'Al-Ibil', 'As Sha', 'Al-Kheil'],
    correctOption: 'Al-Kheil',
    description: "The book about horses is 'Al-Kheil'.",
    slug: 'which-one-of-the-following-book-is-about-horses',
  },
  {
    id: 12,
    questionName:
      'Who wrote the books “Al-Wahoosh”, “Al-Kheil”and”As Sha & Al-Ibli”?',
    options: [
      'Jafar Al-Sadiq',
      'Jabir bin Hayyan',
      'Bu Ali Sina',
      'Abdul Malik Asmai',
    ],
    correctOption: 'Abdul Malik Asmai',
    description:
      "Abdul Malik Asmai wrote the books 'Al-Wahoosh', 'Al-Kheil', 'As Sha', and 'Al-Ibli'.",
    slug: 'who-wrote-the-books-al-wahoosh-al-kheil-and-as-sha-al-ibli',
  },
  {
    id: 13,
    questionName: 'In the West, Bu Ali Sina is also known as',
    options: ['Aviceena', 'Alchemy', 'Greeknot', 'Fredrick'],
    correctOption: 'Aviceena',
    description: 'In the West, Bu Ali Sina is also known as Aviceena.',
    slug: 'in-the-west-bu-ali-sina-is-also-known-as',
  },
  {
    id: 14,
    questionName: 'Who was the first physician',
    options: [
      'Bu Ali Sina',
      'Jabir bin Hayyan',
      'Abdul Malik Asmai',
      'Abdullah bin Javed',
    ],
    correctOption: 'Bu Ali Sina',
    description: 'Bu Ali Sina was one of the first physicians.',
    slug: 'who-was-the-first-physician',
  },
  {
    id: 15,
    questionName: '“Al-Qanun-fi al-Tib” is the famous book of',
    options: [
      'Jabir Bin Hayan',
      'Abdul Malik Asmai',
      'Bu Ali Sina',
      'Dr. Abdul Qadir Khan',
    ],
    correctOption: 'Bu Ali Sina',
    description: "The famous book 'Al-Qanun-fi al-Tib' is by Bu Ali Sina.",
    slug: 'al-qanun-fi-al-tib-is-the-famous-book-of',
  },
  {
    id: 16,
    questionName: 'Who wrote “Al-Nabatat”and”Al-Hayawan” books?',
    options: [
      'Bu Ali Sina',
      'Jabir Bin Hayan',
      'Abdul Malik Asmai',
      'Jafar Al-Sadiq',
    ],
    correctOption: 'Abdul Malik Asmai',
    description: "Abdul Malik Asmai wrote 'Al-Nabatat' and 'Al-Hayawan' books.",
    slug: 'who-wrote-al-nabatat-and-al-hayawan-books',
  },
  {
    id: 17,
    questionName: 'Which one of the following books is about wild animals?',
    options: ['Al Wahoosh', 'Al-Kheil', 'Al-Ibli', 'As Sha'],
    correctOption: 'Al Wahoosh',
    description: "The book about wild animals is 'Al Wahoosh'.",
    slug: 'which-one-of-the-following-books-is-about-wild-animals',
  },
  {
    id: 18,
    questionName: 'Which one of the following books is about sheep?',
    options: ['Al-Kheil', 'As Sha', 'Al-Ibil', 'Al Wahoosh'],
    correctOption: 'As Sha',
    description: "The book about sheep is 'As Sha'.",
    slug: 'which-one-of-the-following-books-is-about-sheep',
  },
  {
    id: 19,
    questionName:
      'The famous Muslim scientist Ibn al-Nafis is famous for the discovery of',
    options: [
      'The mind',
      'Circulatory system',
      'Electromagnetic theory',
      'Taxonomy',
    ],
    correctOption: 'Circulatory system',
    description:
      'Ibn al-Nafis is famous for the discovery of the circulatory system.',
    slug: 'the-famous-muslim-scientist-ibn-al-nafis-is-famous-for-the-discovery-of',
  },
]
