export const class_9_quiz = [
  {
    title: "Punjab Board",
    filter: "punjab-board-biology",
    books: [
      {
        title: "Biology Book",
        link: "/quiz/class-9/",
        filter: "punjab-board-biology",
        keyword: ["", ""],
        description: "",
        chapter: [
          {
            title: "Chapter 1: Introduction to Biology",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-1",
            fileId: "1IyH7xV628yg-oidU52hSXr3cpwMm3X5RrlPoaRnUAs4",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 2: Solving A Biological Problem",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-2",
            fileId: "1Xshm8K23Tev3SHN4OS36JH0a9gsACwY7rWhrBh3GvLo",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 3: Biodiversity",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-3",
            fileId: "19VPY1vpe8t3hZtt8ucRZj9HULE9LPlPkJOoOm3iIbwA",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 4: Cells And Tissues",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-4",
            fileId: "1Hr8t4GnWlCnVmAWjdmZPiSInZ8nZ9NtqSv93LmilhdM",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 5: Cells And Tissues",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-5",
            fileId: "1F49OherTCxttb2lmgQgpGhsExMSgr5ICMw5KGVydVWY",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 6: Enzymes",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-6",
            fileId: "1kgTXvRTPyUe-bz-wwe6TAwR_d9to_83uZsbTLBxRq5A",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 7: Bioenergetics",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-7",
            fileId: "1gwxB9Ji7Q2ZJT2mxCueFSVe5lSVHfnVqRcn_7Zj_nuU",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 8: Nutrition",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-8",
            fileId: "1p9DvmdSMJx5XLzj780e97kNTeX-A9yzkdW8z5eq3GX0",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 9: Transport",
            link: "/quiz/class-9/punjab-board-biology/",
            filter: "chapter-9",
            fileId: "1DCfFYaSvcHnN_b4s4eHdQTonZ8OeCpu7PhD6gDJFuFA",
            keyword: ["", ""],
            description: "",
          },
        ],
      },
      {
        title: "Chemistry Book",
        link: "/quiz/class-9/",
        filter: "punjab-board-chemistry",
        keyword: ["", ""],
        description: "",
        chapter: [
          {
            title: "Chapter 1: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-1",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 2: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-2",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 3: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-3",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 4: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-4",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 5: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-5",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 6: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-6",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 7: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-7",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 8: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-8",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 9: ",
            link: "/quiz/class-9/punjab-board-chemistry/",
            filter: "chapter-9",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
        ],
      },
      {
        title: "Physics Book",
        link: "/quiz/class-9/",
        filter: "punjab-board-physics",
        keyword: ["", ""],
        description: "",
        chapter: [
          {
            title: "Chapter 1: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-1",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 2: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-2",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 3: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-3",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 4: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-4",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 5: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-5",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 6: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-6",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 7: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-7",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 8: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-8",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
          {
            title: "Chapter 9: ",
            link: "/quiz/class-9/punjab-board-physics/",
            filter: "chapter-9",
            fileId: "",
            keyword: ["", ""],
            description: "",
          },
        ],
      },
    ],
  },
];
